### ISSUE TITLE
output directory does not exist

### ISSUE THREAD

**Issue by SimonStevenson** [TeamMETISSE/METISSE#18]
after compiling and running METISSE, I got the following error

At line 62 of file ../src/evolv_metisse.f90 (unit = 120)
Fortran runtime error: Cannot open file './output/evolve_09628M.dat': No such file or directory

It turns out that this is because I did not have an existing output directory. Simply doing 'mkdir output' resolved this issue.

Possible solutions include adding an empty output directory to the repository, adding a note about this to the documentation or configuring the write statement to check and create the output directory if it does not already exist.

**Comment by poojanagrawal** [comment]
Thanks for pointing this out Simon. This has been fixed in https://github.com/TeamMETISSE/METISSE/commit/4b75db8b417e02c604b14f43731e0d50e6f2f0dd
